#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Cookie 通用工具：Netscape txt <-> Playwright json 互转，兼容 #HttpOnly_ 前缀
供 douyin / xhs / tiktok 复用，单源维护
"""
import json
import re
from pathlib import Path
from storage import atomic_text

def netscape_to_playwright(txt_path: Path, json_path: Path) -> int:
    """Netscape txt -> Playwright json 数组，返回条数"""
    txt = Path(txt_path).read_text(encoding="utf-8", errors="replace")
    cookies = []
    for raw in txt.splitlines():
        line = raw.strip()
        if not line:
            continue
        http_only = False
        if line.startswith("#HttpOnly_"):
            line = line[len("#HttpOnly_"):]
            http_only = True
        elif line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            parts = re.split(r"\s+", line)
        if len(parts) < 7:
            continue
        domain, flag, path, secure, expiry, name, value = parts[:7]
        c = {
            "name": name,
            "value": value,
            "domain": domain,
            "path": path,
            "secure": secure == "TRUE",
            "httpOnly": http_only,
        }
        try:
            exp = int(expiry)
            if exp > 0:
                c["expirationDate"] = exp
                c["expires"] = exp
        except Exception:
            pass
        cookies.append(c)
    atomic_text(json_path,json.dumps(cookies,ensure_ascii=False,indent=2))
    return len(cookies)

def load_playwright_cookies(json_path: Path):
    """读取 Playwright json，容错去 #HttpOnly_ 前缀已在转换时处理"""
    p = Path(json_path)
    if not p.exists():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8-sig", errors="replace"))
        out = []
        for c in data:
            try:
                ck = {
                    "name": c["name"],
                    "value": c["value"],
                    "domain": c.get("domain", ".douyin.com"),
                    "path": c.get("path", "/"),
                }
                exp = c.get("expirationDate") or c.get("expires")
                if isinstance(exp, (int, float)) and exp > 0:
                    ck["expires"] = int(exp)
                if c.get("secure"):
                    ck["secure"] = True
                if c.get("httpOnly"):
                    ck["httpOnly"] = True
                # SameSite 需映射为 Playwright 允许值 Strict|Lax|None
                ss = c.get("sameSite")
                if ss:
                    m = {"lax": "Lax", "strict": "Strict", "none": "None", "no_restriction": "None", "no_restriction ": "None"}
                    norm = str(ss).strip().lower()
                    if norm in m:
                        ck["sameSite"] = m[norm]
                    elif str(ss).strip() in ("Lax", "Strict", "None"):
                        ck["sameSite"] = str(ss).strip()
                    # 其他值（如 empty）直接丢弃，避免 add_cookies 报错
                out.append(ck)
            except Exception:
                continue
        return out
    except Exception:
        return []

def playwright_to_netscape(cookies, out_txt: Path):
    """Playwright cookies -> Netscape txt"""
    lines = ["# Netscape HTTP Cookie File", "# http://curl.haxx.se/rfc/cookie_spec.html", "# This file was generated by Playwright"]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = str(int(c.get("expires", c.get("expirationDate", -1))) if c.get("expires", c.get("expirationDate", -1)) != -1 else 0)
        name = c.get("name", "")
        value = c.get("value", "")
        if c.get('httpOnly'):domain='#HttpOnly_'+domain
        lines.append("\t".join([domain, flag, path, secure, expiry, name, value]))
    atomic_text(out_txt,"\n".join(lines))

def report_cookie_status(platform: str, expired: bool, msg: str = ""):
    """写入 work/cookie_status.json 供前端轮询（P1 失败告警）"""
    try:
        from _paths import WORK_DIR
        flag = WORK_DIR / "cookie_status.json"
        try:
            data = json.loads(flag.read_text(encoding="utf-8")) if flag.exists() else {}
        except Exception:
            data = {}
        if expired:
            data[platform] = {"expired": True, "msg": msg, "ts": __import__("time").time()}
        else:
            # 成功则清标记
            data.pop(platform, None)
        flag.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    except Exception:
        pass
